<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>PDO demo</title>
    <link type="text/css" rel="stylesheet" href="css/style.css" />
  </head>
  <body>
   <h1>bONDS DE COMMANDE</h1>
    <section>
      <table>
        <thead>
          <tr>
            <th clospan="1">Commande</th>
            <th colspan="1">Date de commande</th>
            <th colspan="1">Date de livraison</th>
            <th colspan="1">Status</th>
          </tr>
        </thead>
        <tbody>
          <?php ?>
          <tr>
              <td colspan="1">numéro de comande 1</td>
              <td colspan="1">date de la commande 1</td>
              <td colspan="1">date de la livraison 1</td>
              <td colspan="1">Shipped</td>
            </tr>
            <tr>
              <td colspan="1">numéro de comand 2</td>
              <td colspan="1">date de la command 2</td>
              <td colspan="1">date de la livraison 2</td>
              <td colspan="1">not shipped YET</td>
            </tr>
          <?php ?>
        </tbody>
      </table>
    </section>

  </body>
</html>