<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>PDO demo</title>
    <link type="text/css" rel="stylesheet" href="css/style.css" />
  </head>
  <body>
   <h1>Bond de commande</h1>
    <section>
      <table>
        <thead>
          <tr>
            <th clospan="1">Commande</th>
            <th colspan="1">Date de commande</th>
            <th colspan="1">Date de livraison</th>
            <th colspan="1">Status</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach($orders as $key => $value): ?>
          <tr>
              <td colspan="1"><a href="orderForm.php?orderNumber=<?= $value["orderNumber"] ?>"><?= $value["orderNumber"] ?></a></td>
              <td colspan="1"><?= $value["orderDate"] ?></td>
              <td colspan="1"><?= $value["shippedDate"] ?></td>
              <td colspan="1"><?= $value["status"] ?></td>
            </tr>       
          <?php endforeach; ?>
        </tbody>
      </table>
    </section>

  </body>
</html>