<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>orderForm</title>
    <link type="text/css" rel="stylesheet" href="css/style.css">
  </head>
  <body>
    
    <section>
      <header>
      <h1>Bonds de commande<h1>
      <a href="index.php">Retourner à l'acceuil</a>
      </header>
      <article>
        <?php foreach($customer as $key => $value): ?>
         <p><?= $value?></p>  
        <?php endforeach; ?>
      </article>
      <article>
        <table> 
            <thead>
                <tr>
                    <th colspan="1">Produit</th>
                    <th colspan="1">Prix unitaire</th>
                    <th colspan="1">Quantité</th>
                    <th colspan="1">Prix Total</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($orderDet as $key => $value): ?>
                  <tr>
                      <td><?= $value['productName'] ?></td>
                      <td><?= $value['priceEach'] ?></td>
                      <td><?= $value['quantityOrdered'] ?></td>
                      <td><?= $value['totalPrice']?></td>
                      
                </tr>
                <?php  endforeach;  ?>
            </tbody>
        </table>
      </article>
    </section>
  </body>
</htmL>