<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>orderForm</title>
  </head>
  <body>
    <h1><h1>
    <section>
      <table> 
          <thead>
              <tr>
                  <th colspan="1">Produit"</th>
                  <th colspan="1">Prix unitaire</th>
                  <th colspan="1">Quantité</th>
                  <th colspan="1">Prix Total</th>
              </tr>
          </thead>
          <tbody>
              <?php foreach($employees as $key => $value): ?>
                <tr>
                    <td><?= $value['firstName'] ?></td>
                    <td><?= $value['lastName'] ?></td>
                    <td><?= $value['jobTitle']?></td>
                    <td><?= $value['city'] ?></td>
              </tr>
              <?php  endforeach;  ?>
          </tbody>
      </table>
    </section>
  </body>
</htmL>