<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>PDO demo</title>
  </head>
  <body>
    <h1>Liste des employés</h1>

    <table>
       
        <thead>
            <tr>
                <th colspan="1">Prénom</th>
                <th colspan="1">Nom</th>
                <th colspan="1">Fonction</th>
                <th colspan="1">Ville</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($employees as $key => $value): ?>
              <tr>
                  <td><?= $value['firstName'] ?></td>
                  <td><?= $value['lastName'] ?></td>
                  <td><?= $value['jobTitle']?></td>
                  <td><?= $value['city'] ?></td>
             </tr>
            <?php  endforeach;  ?>
        </tbody>
    </table>


  </body>
</html>